"""add external_football_data_org_id to clubs and players

Revision ID: 295383570944
Revises: 8ecbc5e318de
Create Date: 2026-07-06 11:57:27.522659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '295383570944'
down_revision: Union[str, Sequence[str], None] = '8ecbc5e318de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('external_football_data_org_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_clubs_external_football_data_org_id'), 'clubs', ['external_football_data_org_id'], unique=True)
    op.add_column('players', sa.Column('external_football_data_org_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_players_external_football_data_org_id'), 'players', ['external_football_data_org_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_external_football_data_org_id'), table_name='players')
    op.drop_column('players', 'external_football_data_org_id')
    op.drop_index(op.f('ix_clubs_external_football_data_org_id'), table_name='clubs')
    op.drop_column('clubs', 'external_football_data_org_id')
    # ### end Alembic commands ###
