"""add source to player_season_stats

Revision ID: 8ecbc5e318de
Revises: 948787cea288
Create Date: 2026-07-06 09:19:47.535157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ecbc5e318de'
down_revision: Union[str, Sequence[str], None] = '948787cea288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOT: server_default elle eklendi — tabloda zaten satir var (mevcut
    # api_football kayitlari), default'suz NOT NULL ekleme patlar.
    op.add_column(
        'player_season_stats',
        sa.Column('source', sa.String(length=20), nullable=False, server_default='api_football'),
    )
    op.alter_column('player_season_stats', 'source', server_default=None)
    op.drop_constraint(op.f('uq_player_season'), 'player_season_stats', type_='unique')
    op.create_unique_constraint('uq_player_season', 'player_season_stats', ['external_player_id', 'league_id', 'season', 'source'])
    op.create_index(op.f('ix_player_season_stats_source'), 'player_season_stats', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_season_stats_source'), table_name='player_season_stats')
    op.drop_constraint('uq_player_season', 'player_season_stats', type_='unique')
    op.create_unique_constraint(op.f('uq_player_season'), 'player_season_stats', ['external_player_id', 'league_id', 'season'], postgresql_nulls_not_distinct=False)
    op.drop_column('player_season_stats', 'source')
    # ### end Alembic commands ###
