"""add player_season_stats and transfers

Revision ID: 948787cea288
Revises: cd69db2fe0fa
Create Date: 2026-07-05 19:32:51.389604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '948787cea288'
down_revision: Union[str, Sequence[str], None] = 'cd69db2fe0fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_player_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('photo_url', sa.String(length=300), nullable=True),
    sa.Column('club_name', sa.String(length=120), nullable=True),
    sa.Column('club_logo', sa.String(length=300), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('league_name', sa.String(length=80), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_player_id', 'league_id', 'season', name='uq_player_season')
    )
    op.create_index(op.f('ix_player_season_stats_external_player_id'), 'player_season_stats', ['external_player_id'], unique=False)
    op.create_index(op.f('ix_player_season_stats_league_id'), 'player_season_stats', ['league_id'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_player_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(length=120), nullable=False),
    sa.Column('from_club', sa.String(length=120), nullable=True),
    sa.Column('to_club', sa.String(length=120), nullable=True),
    sa.Column('transfer_date', sa.String(length=20), nullable=True),
    sa.Column('fee', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_player_id', 'transfer_date', 'to_club', name='uq_transfer')
    )
    op.create_index(op.f('ix_transfers_external_player_id'), 'transfers', ['external_player_id'], unique=False)
    op.create_index(op.f('ix_transfers_transfer_date'), 'transfers', ['transfer_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfers_transfer_date'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_external_player_id'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_player_season_stats_league_id'), table_name='player_season_stats')
    op.drop_index(op.f('ix_player_season_stats_external_player_id'), table_name='player_season_stats')
    op.drop_table('player_season_stats')
    # ### end Alembic commands ###
