"""initial schema

Revision ID: cd69db2fe0fa
Revises: 
Create Date: 2026-07-04 20:38:55.545893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd69db2fe0fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_api_football_id', sa.Integer(), nullable=True),
    sa.Column('transfermarkt_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('short_name', sa.String(length=40), nullable=True),
    sa.Column('logo_url', sa.String(length=300), nullable=True),
    sa.Column('league', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clubs_country'), 'clubs', ['country'], unique=False)
    op.create_index(op.f('ix_clubs_external_api_football_id'), 'clubs', ['external_api_football_id'], unique=True)
    op.create_index(op.f('ix_clubs_league'), 'clubs', ['league'], unique=False)
    op.create_index(op.f('ix_clubs_name'), 'clubs', ['name'], unique=False)
    op.create_index(op.f('ix_clubs_transfermarkt_id'), 'clubs', ['transfermarkt_id'], unique=False)
    op.create_table('formations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('position_slots', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('photo_url', sa.String(length=300), nullable=True),
    sa.Column('nationality', sa.String(length=60), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coaches_club_id'), 'coaches', ['club_id'], unique=False)
    op.create_index(op.f('ix_coaches_external_id'), 'coaches', ['external_id'], unique=False)
    op.create_table('lineups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('formation_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineups_club_id'), 'lineups', ['club_id'], unique=False)
    op.create_index(op.f('ix_lineups_user_id'), 'lineups', ['user_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_api_football_id', sa.Integer(), nullable=True),
    sa.Column('transfermarkt_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('photo_url', sa.String(length=300), nullable=True),
    sa.Column('position', sa.String(length=4), nullable=False),
    sa.Column('detail_position', sa.String(length=40), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=60), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('market_value', sa.BigInteger(), nullable=True),
    sa.Column('market_value_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_club_id'), 'players', ['club_id'], unique=False)
    op.create_index(op.f('ix_players_external_api_football_id'), 'players', ['external_api_football_id'], unique=True)
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_index(op.f('ix_players_position'), 'players', ['position'], unique=False)
    op.create_index(op.f('ix_players_transfermarkt_id'), 'players', ['transfermarkt_id'], unique=False)
    op.create_table('lineup_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lineup_id', sa.Integer(), nullable=False),
    sa.Column('position_key', sa.String(length=12), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lineup_id'], ['lineups.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lineup_id', 'position_key', name='uq_lineup_position')
    )
    op.create_index(op.f('ix_lineup_slots_lineup_id'), 'lineup_slots', ['lineup_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lineup_slots_lineup_id'), table_name='lineup_slots')
    op.drop_table('lineup_slots')
    op.drop_index(op.f('ix_players_transfermarkt_id'), table_name='players')
    op.drop_index(op.f('ix_players_position'), table_name='players')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_index(op.f('ix_players_external_api_football_id'), table_name='players')
    op.drop_index(op.f('ix_players_club_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_lineups_user_id'), table_name='lineups')
    op.drop_index(op.f('ix_lineups_club_id'), table_name='lineups')
    op.drop_table('lineups')
    op.drop_index(op.f('ix_coaches_external_id'), table_name='coaches')
    op.drop_index(op.f('ix_coaches_club_id'), table_name='coaches')
    op.drop_table('coaches')
    op.drop_table('formations')
    op.drop_index(op.f('ix_clubs_transfermarkt_id'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_name'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_league'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_external_api_football_id'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_country'), table_name='clubs')
    op.drop_table('clubs')
    # ### end Alembic commands ###
