"""Demo/baslangic verisi: 10 buyuk kulup, 2025-26 sezonu kadrolari.

API-Football anahtari olmadan da uygulamanin calisabilmesi icin kullanilir.
Gercek senkronizasyon calistiginda kayitlar external_api_football_id uzerinden
guncellenir (kulup ID'leri gercek API-Football ID'leridir, logolar gercek CDN'den yuklenir).

Oyuncu formati: (isim, rol, detay pozisyon, yas, forma no, uyruk, piyasa degeri M€)
"""

CLUBS: list[dict] = [
    {
        "api_id": 645,
        "name": "Galatasaray",
        "short": "GAL",
        "league": "Süper Lig",
        "country": "Türkiye",
        "coach": ("Okan Buruk", "Türkiye"),
        "players": [
            ("Uğurcan Çakır", "GK", "Kaleci", 29, 1, "Türkiye", 15),
            ("Günay Güvenç", "GK", "Kaleci", 34, 19, "Türkiye", 1),
            ("Davinson Sánchez", "DF", "Stoper", 29, 6, "Kolombiya", 25),
            ("Abdülkerim Bardakcı", "DF", "Stoper", 30, 42, "Türkiye", 15),
            ("Kaan Ayhan", "DF", "Stoper", 30, 4, "Türkiye", 6),
            ("Wilfried Singo", "DF", "Sağ Bek", 24, 2, "Fildişi Sahili", 28),
            ("Ismail Jakobs", "DF", "Sol Bek", 26, 55, "Senegal", 12),
            ("Eren Elmalı", "DF", "Sol Bek", 25, 3, "Türkiye", 9),
            ("Lucas Torreira", "MF", "Ön Libero", 29, 34, "Uruguay", 16),
            ("Gabriel Sara", "MF", "Merkez Orta Saha", 26, 8, "Brezilya", 30),
            ("İlkay Gündoğan", "MF", "Merkez Orta Saha", 34, 7, "Almanya", 9),
            ("Berkan Kutlu", "MF", "Merkez Orta Saha", 27, 25, "Türkiye", 5),
            ("Leroy Sané", "FW", "Sağ Kanat", 29, 10, "Almanya", 35),
            ("Barış Alper Yılmaz", "FW", "Sağ Kanat", 25, 53, "Türkiye", 35),
            ("Yunus Akgün", "FW", "Sol Kanat", 25, 11, "Türkiye", 15),
            ("Roland Sallai", "FW", "Sol Kanat", 28, 20, "Macaristan", 16),
            ("Victor Osimhen", "FW", "Santrfor", 26, 45, "Nijerya", 75),
            ("Mauro Icardi", "FW", "Santrfor", 32, 9, "Arjantin", 8),
        ],
    },
    {
        "api_id": 611,
        "name": "Fenerbahçe",
        "short": "FEN",
        "league": "Süper Lig",
        "country": "Türkiye",
        "coach": ("Domenico Tedesco", "Almanya"),
        "players": [
            ("Ederson", "GK", "Kaleci", 32, 1, "Brezilya", 14),
            ("İrfan Can Eğribayat", "GK", "Kaleci", 27, 54, "Türkiye", 4),
            ("Milan Škriniar", "DF", "Stoper", 30, 37, "Slovakya", 12),
            ("Çağlar Söyüncü", "DF", "Stoper", 29, 23, "Türkiye", 8),
            ("Alexander Djiku", "DF", "Stoper", 30, 15, "Gana", 6),
            ("Jayden Oosterwolde", "DF", "Stoper", 24, 4, "Hollanda", 15),
            ("Archie Brown", "DF", "Sol Bek", 23, 3, "İngiltere", 15),
            ("Nélson Semedo", "DF", "Sağ Bek", 31, 2, "Portekiz", 10),
            ("Mert Müldür", "DF", "Sağ Bek", 26, 41, "Türkiye", 8),
            ("İsmail Yüksek", "MF", "Ön Libero", 26, 5, "Türkiye", 12),
            ("Edson Álvarez", "MF", "Ön Libero", 27, 19, "Meksika", 18),
            ("Fred", "MF", "Merkez Orta Saha", 32, 35, "Brezilya", 9),
            ("Sebastian Szymański", "MF", "On Numara", 26, 10, "Polonya", 18),
            ("Marco Asensio", "MF", "On Numara", 29, 28, "İspanya", 20),
            ("İrfan Can Kahveci", "MF", "On Numara", 30, 17, "Türkiye", 7),
            ("Anderson Talisca", "MF", "On Numara", 31, 94, "Brezilya", 8),
            ("Kerem Aktürkoğlu", "FW", "Sol Kanat", 26, 7, "Türkiye", 22),
            ("Dorgeles Nene", "FW", "Sağ Kanat", 22, 21, "Mali", 18),
            ("Jhon Durán", "FW", "Santrfor", 21, 20, "Kolombiya", 30),
            ("Youssef En-Nesyri", "FW", "Santrfor", 28, 9, "Fas", 18),
        ],
    },
    {
        "api_id": 541,
        "name": "Real Madrid",
        "short": "RMA",
        "league": "La Liga",
        "country": "İspanya",
        "coach": ("Xabi Alonso", "İspanya"),
        "players": [
            ("Thibaut Courtois", "GK", "Kaleci", 33, 1, "Belçika", 22),
            ("Andriy Lunin", "GK", "Kaleci", 26, 13, "Ukrayna", 20),
            ("Trent Alexander-Arnold", "DF", "Sağ Bek", 26, 12, "İngiltere", 70),
            ("Dani Carvajal", "DF", "Sağ Bek", 33, 2, "İspanya", 8),
            ("Éder Militão", "DF", "Stoper", 27, 3, "Brezilya", 40),
            ("Antonio Rüdiger", "DF", "Stoper", 32, 22, "Almanya", 22),
            ("Dean Huijsen", "DF", "Stoper", 20, 24, "İspanya", 70),
            ("Raúl Asencio", "DF", "Stoper", 22, 17, "İspanya", 30),
            ("Álvaro Carreras", "DF", "Sol Bek", 22, 18, "İspanya", 50),
            ("Fran García", "DF", "Sol Bek", 26, 20, "İspanya", 20),
            ("Aurélien Tchouaméni", "MF", "Ön Libero", 25, 14, "Fransa", 90),
            ("Eduardo Camavinga", "MF", "Merkez Orta Saha", 22, 6, "Fransa", 90),
            ("Federico Valverde", "MF", "Merkez Orta Saha", 27, 8, "Uruguay", 130),
            ("Jude Bellingham", "MF", "On Numara", 22, 5, "İngiltere", 180),
            ("Arda Güler", "MF", "On Numara", 20, 15, "Türkiye", 60),
            ("Dani Ceballos", "MF", "Merkez Orta Saha", 28, 19, "İspanya", 12),
            ("Kylian Mbappé", "FW", "Santrfor", 26, 10, "Fransa", 180),
            ("Vinícius Júnior", "FW", "Sol Kanat", 25, 7, "Brezilya", 170),
            ("Rodrygo", "FW", "Sağ Kanat", 24, 11, "Brezilya", 90),
            ("Brahim Díaz", "FW", "Sağ Kanat", 26, 21, "Fas", 30),
            ("Gonzalo García", "FW", "Santrfor", 21, 16, "İspanya", 30),
        ],
    },
    {
        "api_id": 529,
        "name": "Barcelona",
        "short": "BAR",
        "league": "La Liga",
        "country": "İspanya",
        "coach": ("Hansi Flick", "Almanya"),
        "players": [
            ("Joan García", "GK", "Kaleci", 24, 13, "İspanya", 30),
            ("Marc-André ter Stegen", "GK", "Kaleci", 33, 1, "Almanya", 10),
            ("Wojciech Szczęsny", "GK", "Kaleci", 35, 25, "Polonya", 2),
            ("Jules Koundé", "DF", "Sağ Bek", 26, 23, "Fransa", 60),
            ("Pau Cubarsí", "DF", "Stoper", 18, 5, "İspanya", 80),
            ("Ronald Araújo", "DF", "Stoper", 26, 4, "Uruguay", 35),
            ("Andreas Christensen", "DF", "Stoper", 29, 15, "Danimarka", 12),
            ("Eric García", "DF", "Stoper", 24, 24, "İspanya", 20),
            ("Alejandro Balde", "DF", "Sol Bek", 21, 3, "İspanya", 60),
            ("Gerard Martín", "DF", "Sol Bek", 23, 35, "İspanya", 15),
            ("Marc Casadó", "MF", "Ön Libero", 21, 17, "İspanya", 30),
            ("Frenkie de Jong", "MF", "Merkez Orta Saha", 28, 21, "Hollanda", 45),
            ("Pedri", "MF", "Merkez Orta Saha", 22, 8, "İspanya", 140),
            ("Gavi", "MF", "Merkez Orta Saha", 21, 6, "İspanya", 60),
            ("Dani Olmo", "MF", "On Numara", 27, 20, "İspanya", 60),
            ("Fermín López", "MF", "On Numara", 22, 16, "İspanya", 50),
            ("Lamine Yamal", "FW", "Sağ Kanat", 18, 10, "İspanya", 200),
            ("Raphinha", "FW", "Sol Kanat", 28, 11, "Brezilya", 90),
            ("Robert Lewandowski", "FW", "Santrfor", 37, 9, "Polonya", 12),
            ("Ferran Torres", "FW", "Santrfor", 25, 7, "İspanya", 40),
            ("Marcus Rashford", "FW", "Sol Kanat", 27, 14, "İngiltere", 40),
        ],
    },
    {
        "api_id": 50,
        "name": "Manchester City",
        "short": "MCI",
        "league": "Premier League",
        "country": "İngiltere",
        "coach": ("Pep Guardiola", "İspanya"),
        "players": [
            ("Gianluigi Donnarumma", "GK", "Kaleci", 26, 25, "İtalya", 40),
            ("James Trafford", "GK", "Kaleci", 22, 1, "İngiltere", 25),
            ("Rúben Dias", "DF", "Stoper", 28, 3, "Portekiz", 55),
            ("Joško Gvardiol", "DF", "Sol Bek", 23, 24, "Hırvatistan", 80),
            ("John Stones", "DF", "Stoper", 31, 5, "İngiltere", 30),
            ("Nathan Aké", "DF", "Stoper", 30, 6, "Hollanda", 25),
            ("Abdukodir Khusanov", "DF", "Stoper", 21, 45, "Özbekistan", 30),
            ("Nico O'Reilly", "DF", "Sol Bek", 20, 33, "İngiltere", 45),
            ("Matheus Nunes", "DF", "Sağ Bek", 27, 27, "Portekiz", 40),
            ("Rayan Aït-Nouri", "DF", "Sol Bek", 24, 21, "Cezayir", 35),
            ("Rodri", "MF", "Ön Libero", 29, 16, "İspanya", 90),
            ("Nico González", "MF", "Ön Libero", 23, 14, "İspanya", 55),
            ("Tijjani Reijnders", "MF", "Merkez Orta Saha", 27, 4, "Hollanda", 75),
            ("Bernardo Silva", "MF", "On Numara", 31, 20, "Portekiz", 40),
            ("Phil Foden", "MF", "On Numara", 25, 47, "İngiltere", 100),
            ("Rayan Cherki", "MF", "On Numara", 21, 10, "Fransa", 45),
            ("Erling Haaland", "FW", "Santrfor", 25, 9, "Norveç", 180),
            ("Omar Marmoush", "FW", "Santrfor", 26, 7, "Mısır", 60),
            ("Jérémy Doku", "FW", "Sol Kanat", 23, 11, "Belçika", 70),
            ("Savinho", "FW", "Sağ Kanat", 21, 26, "Brezilya", 50),
            ("Oscar Bobb", "FW", "Sağ Kanat", 22, 52, "Norveç", 30),
        ],
    },
    {
        "api_id": 40,
        "name": "Liverpool",
        "short": "LIV",
        "league": "Premier League",
        "country": "İngiltere",
        "coach": ("Arne Slot", "Hollanda"),
        "players": [
            ("Alisson", "GK", "Kaleci", 33, 1, "Brezilya", 20),
            ("Giorgi Mamardashvili", "GK", "Kaleci", 25, 56, "Gürcistan", 25),
            ("Virgil van Dijk", "DF", "Stoper", 34, 4, "Hollanda", 28),
            ("Ibrahima Konaté", "DF", "Stoper", 26, 5, "Fransa", 55),
            ("Joe Gomez", "DF", "Stoper", 28, 2, "İngiltere", 15),
            ("Jeremie Frimpong", "DF", "Sağ Bek", 24, 30, "Hollanda", 40),
            ("Conor Bradley", "DF", "Sağ Bek", 22, 12, "Kuzey İrlanda", 35),
            ("Milos Kerkez", "DF", "Sol Bek", 21, 6, "Macaristan", 45),
            ("Andrew Robertson", "DF", "Sol Bek", 31, 26, "İskoçya", 12),
            ("Ryan Gravenberch", "MF", "Ön Libero", 23, 38, "Hollanda", 90),
            ("Alexis Mac Allister", "MF", "Merkez Orta Saha", 26, 10, "Arjantin", 100),
            ("Dominik Szoboszlai", "MF", "Merkez Orta Saha", 24, 8, "Macaristan", 90),
            ("Curtis Jones", "MF", "Merkez Orta Saha", 24, 17, "İngiltere", 40),
            ("Wataru Endō", "MF", "Ön Libero", 32, 3, "Japonya", 8),
            ("Florian Wirtz", "MF", "On Numara", 22, 7, "Almanya", 140),
            ("Mohamed Salah", "FW", "Sağ Kanat", 33, 11, "Mısır", 55),
            ("Alexander Isak", "FW", "Santrfor", 26, 9, "İsveç", 120),
            ("Hugo Ekitiké", "FW", "Santrfor", 23, 22, "Fransa", 75),
            ("Cody Gakpo", "FW", "Sol Kanat", 26, 18, "Hollanda", 65),
            ("Federico Chiesa", "FW", "Sağ Kanat", 27, 14, "İtalya", 15),
        ],
    },
    {
        "api_id": 42,
        "name": "Arsenal",
        "short": "ARS",
        "league": "Premier League",
        "country": "İngiltere",
        "coach": ("Mikel Arteta", "İspanya"),
        "players": [
            ("David Raya", "GK", "Kaleci", 30, 22, "İspanya", 40),
            ("Kepa Arrizabalaga", "GK", "Kaleci", 31, 13, "İspanya", 8),
            ("William Saliba", "DF", "Stoper", 24, 2, "Fransa", 90),
            ("Gabriel Magalhães", "DF", "Stoper", 27, 6, "Brezilya", 75),
            ("Ben White", "DF", "Sağ Bek", 28, 4, "İngiltere", 30),
            ("Jurriën Timber", "DF", "Sağ Bek", 24, 12, "Hollanda", 60),
            ("Riccardo Calafiori", "DF", "Sol Bek", 23, 33, "İtalya", 45),
            ("Myles Lewis-Skelly", "DF", "Sol Bek", 19, 49, "İngiltere", 55),
            ("Cristhian Mosquera", "DF", "Stoper", 21, 3, "İspanya", 30),
            ("Declan Rice", "MF", "Merkez Orta Saha", 26, 41, "İngiltere", 120),
            ("Martín Zubimendi", "MF", "Ön Libero", 26, 36, "İspanya", 60),
            ("Mikel Merino", "MF", "Merkez Orta Saha", 29, 23, "İspanya", 30),
            ("Christian Nørgaard", "MF", "Ön Libero", 31, 16, "Danimarka", 12),
            ("Martin Ødegaard", "MF", "On Numara", 26, 8, "Norveç", 85),
            ("Ethan Nwaneri", "MF", "On Numara", 18, 22, "İngiltere", 55),
            ("Bukayo Saka", "FW", "Sağ Kanat", 24, 7, "İngiltere", 150),
            ("Gabriel Martinelli", "FW", "Sol Kanat", 24, 11, "Brezilya", 50),
            ("Leandro Trossard", "FW", "Sol Kanat", 30, 19, "Belçika", 30),
            ("Eberechi Eze", "FW", "Sol Kanat", 27, 10, "İngiltere", 60),
            ("Noni Madueke", "FW", "Sağ Kanat", 23, 20, "İngiltere", 55),
            ("Viktor Gyökeres", "FW", "Santrfor", 27, 14, "İsveç", 75),
            ("Kai Havertz", "FW", "Santrfor", 26, 29, "Almanya", 50),
        ],
    },
    {
        "api_id": 157,
        "name": "Bayern München",
        "short": "BAY",
        "league": "Bundesliga",
        "country": "Almanya",
        "coach": ("Vincent Kompany", "Belçika"),
        "players": [
            ("Manuel Neuer", "GK", "Kaleci", 39, 1, "Almanya", 4),
            ("Jonas Urbig", "GK", "Kaleci", 22, 26, "Almanya", 12),
            ("Dayot Upamecano", "DF", "Stoper", 26, 2, "Fransa", 55),
            ("Kim Min-jae", "DF", "Stoper", 28, 3, "Güney Kore", 35),
            ("Jonathan Tah", "DF", "Stoper", 29, 4, "Almanya", 30),
            ("Alphonso Davies", "DF", "Sol Bek", 24, 19, "Kanada", 45),
            ("Raphaël Guerreiro", "DF", "Sol Bek", 31, 22, "Portekiz", 10),
            ("Josip Stanišić", "DF", "Sağ Bek", 25, 44, "Hırvatistan", 30),
            ("Sacha Boey", "DF", "Sağ Bek", 24, 23, "Fransa", 20),
            ("Konrad Laimer", "DF", "Sağ Bek", 28, 27, "Avusturya", 22),
            ("Joshua Kimmich", "MF", "Ön Libero", 30, 6, "Almanya", 50),
            ("Aleksandar Pavlović", "MF", "Ön Libero", 21, 45, "Almanya", 60),
            ("Leon Goretzka", "MF", "Merkez Orta Saha", 30, 8, "Almanya", 20),
            ("Tom Bischof", "MF", "Merkez Orta Saha", 20, 20, "Almanya", 30),
            ("Jamal Musiala", "MF", "On Numara", 22, 10, "Almanya", 130),
            ("Michael Olise", "FW", "Sağ Kanat", 23, 17, "Fransa", 110),
            ("Serge Gnabry", "FW", "Sağ Kanat", 30, 7, "Almanya", 22),
            ("Luis Díaz", "FW", "Sol Kanat", 28, 14, "Kolombiya", 70),
            ("Harry Kane", "FW", "Santrfor", 32, 9, "İngiltere", 90),
            ("Nicolas Jackson", "FW", "Santrfor", 24, 11, "Senegal", 50),
        ],
    },
    {
        "api_id": 85,
        "name": "Paris Saint-Germain",
        "short": "PSG",
        "league": "Ligue 1",
        "country": "Fransa",
        "coach": ("Luis Enrique", "İspanya"),
        "players": [
            ("Lucas Chevalier", "GK", "Kaleci", 24, 30, "Fransa", 40),
            ("Matvey Safonov", "GK", "Kaleci", 26, 39, "Rusya", 20),
            ("Marquinhos", "DF", "Stoper", 31, 5, "Brezilya", 35),
            ("Willian Pacho", "DF", "Stoper", 23, 51, "Ekvador", 60),
            ("Illia Zabarnyi", "DF", "Stoper", 23, 6, "Ukrayna", 55),
            ("Lucas Beraldo", "DF", "Stoper", 21, 35, "Brezilya", 20),
            ("Achraf Hakimi", "DF", "Sağ Bek", 26, 2, "Fas", 65),
            ("Nuno Mendes", "DF", "Sol Bek", 23, 25, "Portekiz", 65),
            ("Lucas Hernández", "DF", "Sol Bek", 29, 21, "Fransa", 15),
            ("Vitinha", "MF", "Merkez Orta Saha", 25, 17, "Portekiz", 90),
            ("João Neves", "MF", "Merkez Orta Saha", 20, 87, "Portekiz", 80),
            ("Fabián Ruiz", "MF", "Merkez Orta Saha", 29, 8, "İspanya", 50),
            ("Warren Zaïre-Emery", "MF", "Merkez Orta Saha", 19, 33, "Fransa", 60),
            ("Lee Kang-in", "MF", "On Numara", 24, 19, "Güney Kore", 45),
            ("Senny Mayulu", "MF", "On Numara", 19, 24, "Fransa", 25),
            ("Ousmane Dembélé", "FW", "Santrfor", 28, 10, "Fransa", 90),
            ("Khvicha Kvaratskhelia", "FW", "Sol Kanat", 24, 7, "Gürcistan", 80),
            ("Bradley Barcola", "FW", "Sol Kanat", 23, 29, "Fransa", 65),
            ("Désiré Doué", "FW", "Sağ Kanat", 20, 14, "Fransa", 90),
            ("Gonçalo Ramos", "FW", "Santrfor", 24, 9, "Portekiz", 35),
        ],
    },
    {
        "api_id": 505,
        "name": "Inter",
        "short": "INT",
        "league": "Serie A",
        "country": "İtalya",
        "coach": ("Cristian Chivu", "Romanya"),
        "players": [
            ("Yann Sommer", "GK", "Kaleci", 36, 1, "İsviçre", 4),
            ("Josep Martínez", "GK", "Kaleci", 27, 13, "İspanya", 12),
            ("Alessandro Bastoni", "DF", "Stoper", 26, 95, "İtalya", 75),
            ("Francesco Acerbi", "DF", "Stoper", 37, 15, "İtalya", 3),
            ("Stefan de Vrij", "DF", "Stoper", 33, 6, "Hollanda", 4),
            ("Benjamin Pavard", "DF", "Stoper", 29, 28, "Fransa", 25),
            ("Manuel Akanji", "DF", "Stoper", 30, 25, "İsviçre", 30),
            ("Denzel Dumfries", "DF", "Sağ Kanat Bek", 29, 2, "Hollanda", 50),
            ("Federico Dimarco", "DF", "Sol Kanat Bek", 27, 32, "İtalya", 45),
            ("Carlos Augusto", "DF", "Sol Bek", 26, 30, "Brezilya", 22),
            ("Nicolò Barella", "MF", "Merkez Orta Saha", 28, 23, "İtalya", 75),
            ("Hakan Çalhanoğlu", "MF", "Ön Libero", 31, 20, "Türkiye", 30),
            ("Henrikh Mkhitaryan", "MF", "Merkez Orta Saha", 36, 22, "Ermenistan", 4),
            ("Petar Sučić", "MF", "Merkez Orta Saha", 21, 8, "Hırvatistan", 30),
            ("Piotr Zieliński", "MF", "Merkez Orta Saha", 31, 7, "Polonya", 12),
            ("Davide Frattesi", "MF", "Merkez Orta Saha", 25, 16, "İtalya", 35),
            ("Lautaro Martínez", "FW", "Santrfor", 28, 10, "Arjantin", 95),
            ("Marcus Thuram", "FW", "Santrfor", 28, 9, "Fransa", 75),
            ("Ange-Yoan Bonny", "FW", "Santrfor", 21, 14, "Fransa", 30),
            ("Francesco Pio Esposito", "FW", "Santrfor", 20, 94, "İtalya", 30),
        ],
    },
]
